global_costmap:
   global_frame: map
   robot_base_frame: base_link
   update_frequency: 3.0
   publish_frequency: 2.0
   static_map: true
   rolling_window: false
   resolution: 0.05
   transform_tolerance: 10.0
   map_type: costmap

   inflation_radius: 0.3
   cost_scaling_factor: 0.55